# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies for the project
    - name: Restore dependencies
      run: dotnet restore CyberEssentialsApp/CyberEssentialsApp.csproj

    # Build the application
    - name: Build
      run: dotnet build CyberEssentialsApp/CyberEssentialsApp.csproj --no-restore

    # Run unit tests
    - name: Test
      run: dotnet test CyberEssentialsApp/CyberEssentialsApp.csproj --no-build --verbosity normal
